# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - spring-mysql
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 2255:3306                    # This is the port inside the MySQL container where the MySQL service is listening.
                                    # Any traffic sent to port 3307 on the host will be forwarded to port 3306 inside the container.
    networks:
      - spring-mysql
networks:
  spring-mysql: